//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentrumHandlowe
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObiektDoWynajecia : Korytarz
    {
        public string TypDzialalnosci { get; set; }
        public Nullable<decimal> CenaWynajmu { get; set; }
        public Nullable<System.DateTime> RozpWynajmu { get; set; }
        public Nullable<System.DateTime> ZakWynajmu { get; set; }
    }
}
